# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52258ca558ee30b5f66a2ebec81f66655e390595390ab2976d9189daed8951686e01af7ac0eaa8f26c5784287c1559e9d26fbaf10082ff0b626415b468048818

test:
  secret_key_base: 487ebc5cf5682d4cdd4480ec78a7787806697d2bd203204708a5fc58e6541711053f9cc5151c6531eebe98f09f0a9e5dbbe9ebcc5b89c114fd09e6b63f40c7ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
